# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Codestyle and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: {% raw %}${{ matrix.platform }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v2
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
    - name: Lint with Black
      run: |
        black --check --diff hermes_{{ cookiecutter.instr_name }}
    - name: flake8
      run: |
        flake8 --count hermes_{{ cookiecutter.instr_name }}


