# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Building Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    #{% raw %}
    runs-on: ${{ matrix.platform }}
    #{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      #{% raw %}
    - name: Set up Python ${{ matrix.python-version }}
      #{% endraw %}

      uses: actions/setup-python@v2
      with:
        #{% raw %}
        python-version: ${{ matrix.python-version }}
        #{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[docs]
    - name: Build docs
      working-directory: ./docs
      run: make html
