# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: {% raw %}${{ matrix.platform }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v2
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]
    - name: Run tests
      run: pytest --pyargs hermes_{{ cookiecutter.instr_name }} --cov hermes_{{ cookiecutter.instr_name }}
      env:
        PLATFORM: ${{ matrix.platform }}
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
